;;; misc/config-publishing/doom-one-light-engraved-theme.el -*- lexical-binding: t; -*-

(require 'engrave-faces)

(add-to-list 'engrave-faces-themes
             '(doom-one-light ; Comments are slightly darkened for readability
               (default                             :short "default"             :slug "D"   :foreground "#383a42" :background "#fafafa" :slant normal :weight normal)
               (variable-pitch                      :short "var-pitch"           :slug "vp"  :height 176)
               (shadow                              :short "shadow"              :slug "h"   :foreground "#84888b")
               (success                             :short "success"             :slug "sc"  :foreground "#50a14f")
               (warning                             :short "warning"             :slug "w"   :foreground "#986801")
               (error                               :short "error"               :slug "e"   :foreground "#e45649")
               (link                                :short "link"                :slug "l"   :foreground "#4078f2" :weight bold)
               (link-visited                        :short "link"                :slug "lv"  :foreground "#8b008b" :weight bold)
               (highlight                           :short "link"                :slug "hi"  :foreground "#f0f0f0" :background "#4078f2")
               (font-lock-comment-face              :short "fl-comment"          :slug "c"   :foreground "#84888b")
               (font-lock-comment-delimiter-face    :short "fl-comment-delim"    :slug "cd"  :foreground "#84888b")
               (font-lock-string-face               :short "fl-string"           :slug "s"   :foreground "#50a14f")
               (font-lock-doc-face                  :short "fl-doc"              :slug "d"   :foreground "#727578" :slant italic)
               (font-lock-doc-markup-face           :short "fl-doc-markup"       :slug "m"   :foreground "#b751b6")
               (font-lock-keyword-face              :short "fl-keyword"          :slug "k"   :foreground "#e45649")
               (font-lock-builtin-face              :short "fl-builtin"          :slug "b"   :foreground "#a626a4")
               (font-lock-function-name-face        :short "fl-function"         :slug "f"   :foreground "#a626a4")
               (font-lock-variable-name-face        :short "fl-variable"         :slug "v"   :foreground "#6a1868")
               (font-lock-type-face                 :short "fl-type"             :slug "t"   :foreground "#986801")
               (font-lock-constant-face             :short "fl-constant"         :slug "o"   :foreground "#b751b6")
               (font-lock-warning-face              :short "fl-warning"          :slug "wr"  :foreground "#986801")
               (font-lock-negation-char-face        :short "fl-neg-char"         :slug "nc"  :foreground "#4078f2" :weight bold)
               (font-lock-preprocessor-face         :short "fl-preprocessor"     :slug "pp"  :foreground "#4078f2" :weight bold)
               (font-lock-regexp-grouping-construct :short "fl-regexp"           :slug "rc"  :foreground "#4078f2" :weight bold)
               (font-lock-regexp-grouping-backslash :short "fl-regexp-backslash" :slug "rb"  :foreground "#4078f2" :weight bold)
               (org-block                           :short "org-block"           :slug "ob"  :background "#e7e7e7")
               (org-block-begin-line                :short "org-block-begin"     :slug "obb" :background "#e7e7e7" :slant italic)
               (org-block-end-line                  :short "org-block-end"       :slug "obe" :background "#e7e7e7" :slant italic)
               (outline-1                           :short "outline-1"           :slug "Oa"  :foreground "#e45649" :weight extra-bold    :height 1.25)
               (outline-2                           :short "outline-2"           :slug "Ob"  :foreground "#da8548" :weight bold          :height 1.15)
               (outline-3                           :short "outline-3"           :slug "Oc"  :foreground "#b751b6" :weight bold          :height 1.12)
               (outline-4                           :short "outline-4"           :slug "Od"  :foreground "#6f99f5" :weight semi-bold     :height 1.09)
               (outline-5                           :short "outline-5"           :slug "Oe"  :foreground "#bc5cba" :weight semi-bold     :height 1.06)
               (outline-6                           :short "outline-6"           :slug "Of"  :foreground "#9fbbf8" :weight semi-bold     :height 1.03)
               (outline-7                           :short "outline-7"           :slug "Og"  :foreground "#d292d1" :weight bold)
               (outline-8                           :short "outline-8"           :slug "Oh"  :foreground "#d8e4fc" :weight semi-bold)
               (highlight-numbers-number            :short "hl-number"           :slug "hn"  :foreground "#da8548" :weight bold)
               (highlight-quoted-quote              :short "hl-qquote"           :slug "hq"  :foreground "#4078f2")
               (highlight-quoted-symbol             :short "hl-qsymbol"          :slug "hs"  :foreground "#986801")
               (rainbow-delimiters-depth-1-face     :short "rd-1"                :slug "rda" :foreground "#4078f2")
               (rainbow-delimiters-depth-2-face     :short "rd-2"                :slug "rdb" :foreground "#a626a4")
               (rainbow-delimiters-depth-3-face     :short "rd-3"                :slug "rdc" :foreground "#50a14f")
               (rainbow-delimiters-depth-4-face     :short "rd-4"                :slug "rdd" :foreground "#b751b6")
               (rainbow-delimiters-depth-5-face     :short "rd-5"                :slug "rde" :foreground "#4db5bd")
               (rainbow-delimiters-depth-6-face     :short "rd-6"                :slug "rdf" :foreground "#4078f2")
               (rainbow-delimiters-depth-7-face     :short "rd-7"                :slug "rdg" :foreground "#a626a4")
               (rainbow-delimiters-depth-8-face     :short "rd-8"                :slug "rdh" :foreground "#50a14f")
               (rainbow-delimiters-depth-9-face     :short "rd-9"                :slug "rdi" :foreground "#b751b6")))
